#!/usr/bin/env bash

if ! type -p docker >/dev/null 2>&1; then
  echo "docker is missing" 1>&2
  exit 1
fi

if ! type -p docker-compose >/dev/null 2>&1; then
  echo "docker-compose is missing" 1>&2
  exit 1
fi